### ISSUE TITLE
Signals for Very hot/cold

### ISSUE THREAD

**Issue by sulkhanp** [CryptoSignal/crypto-signal#202]
I think it would be nice to support extreme values such as RSI<10 and RSI>90 to send signals such as very hot and very cold. Currently, you do get 'hot' and 'cold' signals, but they don't tell you to much. By changing values and configuring the numbers, you will lose the ability to track lower values, so I don't see why we don't have this feature yet. Thoughts?

**Comment by jrbartola** [comment]
I don't think adding this as a feature would be particularly useful. If you want to change the value at which the hot and cold signals are active, simply modify the respective thresholds in the configuration file. We've added a great degree of flexibility to each signal, so it's relatively easy to filter out ranges of values you don't care about.

That being said, it is possible to adopt a non-binary signal system. Instead of having just two values (hot/cold), we could assign a number in the range [0,1] to each signal and impose thresholds in that way. Unfortunately I don't really see a reason for doing this at the moment, as anything having to do with probability usually needs to be backed by reliable data (which in asset trading is basically non-existent :P)

**Comment by shads2** [comment]
I feel indifferently about this feature at this point in time, I see no harm in implementing it. But as @jrbartola pointed out you can tune the metrics to whatever threshold you care about and for most indicators very hot and very cold are not meaningful.

I am happy to leave this open, but I don't see it topping my priority list any time soon. If some one else wants to make a PR or if more of the community want to add their voice to this feature request then I am happy listen.

**Comment by shads2** [comment]
I am closing this issue as a won't fix. For most indicators this is not useful and at this stage without a higher degree of community demand I have no interest in implementing it.
