### ISSUE TITLE
VWAP value is incorrect in new analyzer structure

### ISSUE THREAD

**Issue by rhamnett** [CryptoSignal/crypto-signal#258]
Implementation looks to have changed from my original and is producing an erroneous value.  BTC today is circa 9k but VWAP is saying around 14k.

Perhaps revert to my original calculation logic.

Cheers

**Comment by shads2** [comment]
The original calculation logic ignored the period_count and didn't produce a dataframe of time indexed results, so it was no longer possible to use as that is that is now expected as a result. The intention was create the same behaviour correcting those issues.

The new formula contained a bug where the cumulative sum of values was being taken at the wrong point in the calculation... this should be fixed in https://github.com/CryptoSignal/crypto-signal/pull/261

**Comment by shads2** [comment]
merged
