### ISSUE TITLE
Pivot Reversal Indicator - feature

### ISSUE THREAD

**Issue by tomthedude** [CryptoSignal/crypto-signal#275]
Hello,
is it possible to add the PRI (or PRS) - Pivot Reversal Indicator?
is it a part of ta-lib?
thanks :)

**Comment by shads2** [comment]
This is better known as support / resistance https://github.com/CryptoSignal/crypto-signal/issues/219 . Of all indicators to implement this is by far the hardest and most precarious, no technical analysis library that I have ever seen implements it out of the box because getting it right requires very specific tuning to the market you are analysing.

I am going to close this because we already have an open feature request for this.
