### ISSUE TITLE
Is there a way to install it without DOCKER ?

### ISSUE THREAD

**Issue by bluetyphoon77** [CryptoSignal/Crypto-Signal#457]
How could we do that ?
I'd like to test it in PythonAnywhere which is ot offering docker option
thanks in advance

**Comment by ahmetax** [comment]
1. Create a virtual environment in the Crypto-Signal directory using the following command:
      python3 -m venv env
2.  Activate the environment:
      source env/bin/activate
3.  pip install --upgrade pip
4.  cd app
5.  pip install -r requirements-step-1.txt
6.  pip install -r requirements-step-2.txt
7.  In order to run: python app.py
(Note: Give enough permissions to the chart directory and the files in it. )
After installing virt env and required libraries in it, you can run the script with the commands (in Crypto-Signal directory):
source env/bin/activate
cd app
python app.py
